### ISSUE TITLE
Sorry 

### ISSUE THREAD

**Issue by petronije2002** [natchu/designAlgo#1]
Hi, sorry for writing here, but I could not find better way. I have seen you were working on Autotask CreateAttachment Issue.... Would you please tell me how can I make one? I have spent days on it, and it still does not work. I am using atws...

**Comment by natchu** [comment]
No worries. You will need use the MessagePlugin in suds client or something similar to update the soap xml so that there is type associated with each attribute. Only this will push through the xml successfully. I used the marhsalled in suds Message Plugin

**Comment by petronije2002** [comment]
Thank you for your reply. 

I have just solved it. 

create_attach = Raw("""<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Header>
    <AutotaskIntegrations xmlns="http://autotask.net/ATWS/v1_6/">
      <IntegrationCode>FLVV64YRHYOBF7HNHIVHMXTVOHA</IntegrationCode>
    </AutotaskIntegrations>
  </soap:Header>
  <soap:Body>
    <CreateAttachment xmlns="http://autotask.net/ATWS/v1_6/">
      <attachment>
        <Info>
          <FullPath xsi:type="xsd:string">test.png</FullPath>
          <ParentID xsi:type="xsd:string">58689</ParentID>
          <ParentType xsi:type="xsd:string">4</ParentType>
          <Publish xsi:type="xsd:string">2</Publish>
          <Title xsi:type="xsd:string">Ticket Requirements Document</Title>
          <Type xsi:type="xsd:string">FILE_ATTACHMENT</Type>
        </Info>
        <Data>{}</Data>
      </attachment>
    </CreateAttachment>
  </soap:Body>
</soap:Envelope>""".format(data_))


I used requests, to send SOAP messages.


import requests
url="https://webservices19.autotask.net/ATServices/1.6/atws.asmx"
#headers = {'content-type': 'application/soap+xml'}

usrPass = b"rapportage_api@PQRSB82219.NL:vyHPa57nuRqZ5LfqWTza"
b64Val = base64.b64encode(usrPass)
headers = {"Authorization" : "Basic %s" % encoded_u} 


headers['content-type']= 'text/xml'



response = requests.post(url,data=create_attach,headers=headers)

Once again, thank you.

Petar
